jdbc.url=jdbc:clickhouse://127.0.0.1:8123/yelp
jdbc.username=default
jdbc.password=
jdbc.driver=com.clickhouse.jdbc.ClickHouseDriver


# 125385
load.data.problem.path=data/problem.csv
load.data.problem.batchSize=500
load.data.problem.startColumnIndex=500
load.data.problem.endColumnIndex=125385



# 150243
load.data.business.path=data/business_mf.csv
load.data.business.batchSize=1000
load.data.business.startColumnIndex=50000
load.data.business.endColumnIndex=150243


# 851033
load.data.tip.path=data/tip/part_9.csv
load.data.tip.batchSize=1000
load.data.tip.startColumnIndex=0
load.data.tip.endColumnIndex=100000
load.data.tip.count=800000

# pre=100000   4237544  only insert 400w
load.data.review.path=data/review/part_17.csv
load.data.review.batchSize=1000
load.data.review.startColumnIndex=0
load.data.review.endColumnIndex=100000
load.data.review.count=1600000


