jdbc.url=jdbc:dingo:thin:url=127.0.0.1:8765/dingo
jdbc.username=root
jdbc.password=
jdbc.driver=io.dingodb.driver.client.DingoDriverClient

# 150243
load.data.business.path=data/business_mf.csv
load.data.business.batchSize=500
load.data.business.startColumnIndex=75000
load.data.business.endColumnIndex=150243

# 12538512
load.data.problem.path=data/problem.csv
load.data.problem.batchSize=500
load.data.problem.startColumnIndex=100000
load.data.problem.endColumnIndex=125385

# 851033
load.data.tip.path=data/tip/part_1.csv
load.data.tip.batchSize=500
load.data.tip.startColumnIndex=0
load.data.tip.endColumnIndex=50000
load.data.tip.count=0

# pre=100000   4237544
load.data.review.path=data/review/part_1.csv
load.data.review.batchSize=500
load.data.review.startColumnIndex=0
load.data.review.endColumnIndex=50000
load.data.review.count=0


